//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class CollisionEventMsg : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/CollisionEvent";
        public override string RosMessageName => k_RosMessageName;

        //  Published by Unity on /sim/collision when the robot touches something.
        //  Unity debounces repeated contact with the same object to 1 s.
        public const string TAG_WALL = "Wall";
        public const string TAG_SHELF = "Shelf";
        public const string TAG_OBSTACLE = "Obstacle";
        public const string TAG_NPC = "NPC";
        public Std.HeaderMsg header;
        //  stamp = sim time of first contact
        public string other_tag;
        //  one of the TAG_* constants
        public Geometry.PointMsg contact;
        //  contact point, map frame

        public CollisionEventMsg()
        {
            this.header = new Std.HeaderMsg();
            this.other_tag = "";
            this.contact = new Geometry.PointMsg();
        }

        public CollisionEventMsg(Std.HeaderMsg header, string other_tag, Geometry.PointMsg contact)
        {
            this.header = header;
            this.other_tag = other_tag;
            this.contact = contact;
        }

        public static CollisionEventMsg Deserialize(MessageDeserializer deserializer) => new CollisionEventMsg(deserializer);

        private CollisionEventMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.other_tag);
            this.contact = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.other_tag);
            serializer.Write(this.contact);
        }

        public override string ToString()
        {
            return "CollisionEventMsg: " +
            "\nheader: " + header.ToString() +
            "\nother_tag: " + other_tag.ToString() +
            "\ncontact: " + contact.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
