//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class RunEventMsg : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/RunEvent";
        public override string RosMessageName => k_RosMessageName;

        //  One discrete event inside a run. Maps to a row in the run_events table.
        public const string TYPE_COLLISION = "collision";
        public const string TYPE_REPLAN = "replan";
        public const string TYPE_RECOVERY = "recovery";
        public const string TYPE_WARNING = "warning";
        public string event_type;
        //  one of the TYPE_* constants
        public double sim_time_s;
        //  seconds since run start
        public string payload_json;
        //  type-specific detail, e.g. {"other_tag":"NPC"}; "" if none

        public RunEventMsg()
        {
            this.event_type = "";
            this.sim_time_s = 0.0;
            this.payload_json = "";
        }

        public RunEventMsg(string event_type, double sim_time_s, string payload_json)
        {
            this.event_type = event_type;
            this.sim_time_s = sim_time_s;
            this.payload_json = payload_json;
        }

        public static RunEventMsg Deserialize(MessageDeserializer deserializer) => new RunEventMsg(deserializer);

        private RunEventMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.event_type);
            deserializer.Read(out this.sim_time_s);
            deserializer.Read(out this.payload_json);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.event_type);
            serializer.Write(this.sim_time_s);
            serializer.Write(this.payload_json);
        }

        public override string ToString()
        {
            return "RunEventMsg: " +
            "\nevent_type: " + event_type.ToString() +
            "\nsim_time_s: " + sim_time_s.ToString() +
            "\npayload_json: " + payload_json.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
