//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class RunSummaryMsg : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/RunSummary";
        public override string RosMessageName => k_RosMessageName;

        //  Everything measured for one episode. Maps 1:1 to a row in the runs table
        //  plus its run_events. Float metrics that were not measured are NaN (stored as NULL).
        public const string OUTCOME_SUCCESS = "success";
        public const string OUTCOME_FAIL = "fail";
        public const string FAIL_NAV_ABORTED = "nav_aborted";
        public const string FAIL_TIMEOUT = "timeout";
        public const string FAIL_ITEM_ERROR = "item_error";
        public const string FAIL_BRIDGE_LOST = "bridge_lost";
        public int task_id;
        public string scenario_id;
        //  S-00 .. S-05
        public string local_planner;
        //  dwa | teb
        public string outcome;
        //  OUTCOME_*
        public string fail_reason;
        //  FAIL_* when outcome = fail, "" on success
        public double start_x;
        //  robot start pose, map frame
        public double start_y;
        public uint collisions;
        public uint replans;
        public uint recoveries;
        public double min_clearance_m;
        public double path_length_m;
        public double baseline_m;
        //  |start->shelf| + |shelf->dropoff|
        public double path_ratio;
        //  path_length_m / baseline_m
        public double duration_s;
        //  sim time, dispatch -> release or failure
        public double dropoff_mean_speed_mps;
        //  drop-off leg only
        public TimeMsg started_at;
        public TimeMsg ended_at;
        public RunEventMsg[] events;

        public RunSummaryMsg()
        {
            this.task_id = 0;
            this.scenario_id = "";
            this.local_planner = "";
            this.outcome = "";
            this.fail_reason = "";
            this.start_x = 0.0;
            this.start_y = 0.0;
            this.collisions = 0;
            this.replans = 0;
            this.recoveries = 0;
            this.min_clearance_m = 0.0;
            this.path_length_m = 0.0;
            this.baseline_m = 0.0;
            this.path_ratio = 0.0;
            this.duration_s = 0.0;
            this.dropoff_mean_speed_mps = 0.0;
            this.started_at = new TimeMsg();
            this.ended_at = new TimeMsg();
            this.events = new RunEventMsg[0];
        }

        public RunSummaryMsg(int task_id, string scenario_id, string local_planner, string outcome, string fail_reason, double start_x, double start_y, uint collisions, uint replans, uint recoveries, double min_clearance_m, double path_length_m, double baseline_m, double path_ratio, double duration_s, double dropoff_mean_speed_mps, TimeMsg started_at, TimeMsg ended_at, RunEventMsg[] events)
        {
            this.task_id = task_id;
            this.scenario_id = scenario_id;
            this.local_planner = local_planner;
            this.outcome = outcome;
            this.fail_reason = fail_reason;
            this.start_x = start_x;
            this.start_y = start_y;
            this.collisions = collisions;
            this.replans = replans;
            this.recoveries = recoveries;
            this.min_clearance_m = min_clearance_m;
            this.path_length_m = path_length_m;
            this.baseline_m = baseline_m;
            this.path_ratio = path_ratio;
            this.duration_s = duration_s;
            this.dropoff_mean_speed_mps = dropoff_mean_speed_mps;
            this.started_at = started_at;
            this.ended_at = ended_at;
            this.events = events;
        }

        public static RunSummaryMsg Deserialize(MessageDeserializer deserializer) => new RunSummaryMsg(deserializer);

        private RunSummaryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.scenario_id);
            deserializer.Read(out this.local_planner);
            deserializer.Read(out this.outcome);
            deserializer.Read(out this.fail_reason);
            deserializer.Read(out this.start_x);
            deserializer.Read(out this.start_y);
            deserializer.Read(out this.collisions);
            deserializer.Read(out this.replans);
            deserializer.Read(out this.recoveries);
            deserializer.Read(out this.min_clearance_m);
            deserializer.Read(out this.path_length_m);
            deserializer.Read(out this.baseline_m);
            deserializer.Read(out this.path_ratio);
            deserializer.Read(out this.duration_s);
            deserializer.Read(out this.dropoff_mean_speed_mps);
            this.started_at = TimeMsg.Deserialize(deserializer);
            this.ended_at = TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.events, RunEventMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.scenario_id);
            serializer.Write(this.local_planner);
            serializer.Write(this.outcome);
            serializer.Write(this.fail_reason);
            serializer.Write(this.start_x);
            serializer.Write(this.start_y);
            serializer.Write(this.collisions);
            serializer.Write(this.replans);
            serializer.Write(this.recoveries);
            serializer.Write(this.min_clearance_m);
            serializer.Write(this.path_length_m);
            serializer.Write(this.baseline_m);
            serializer.Write(this.path_ratio);
            serializer.Write(this.duration_s);
            serializer.Write(this.dropoff_mean_speed_mps);
            serializer.Write(this.started_at);
            serializer.Write(this.ended_at);
            serializer.WriteLength(this.events);
            serializer.Write(this.events);
        }

        public override string ToString()
        {
            return "RunSummaryMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\nscenario_id: " + scenario_id.ToString() +
            "\nlocal_planner: " + local_planner.ToString() +
            "\noutcome: " + outcome.ToString() +
            "\nfail_reason: " + fail_reason.ToString() +
            "\nstart_x: " + start_x.ToString() +
            "\nstart_y: " + start_y.ToString() +
            "\ncollisions: " + collisions.ToString() +
            "\nreplans: " + replans.ToString() +
            "\nrecoveries: " + recoveries.ToString() +
            "\nmin_clearance_m: " + min_clearance_m.ToString() +
            "\npath_length_m: " + path_length_m.ToString() +
            "\nbaseline_m: " + baseline_m.ToString() +
            "\npath_ratio: " + path_ratio.ToString() +
            "\nduration_s: " + duration_s.ToString() +
            "\ndropoff_mean_speed_mps: " + dropoff_mean_speed_mps.ToString() +
            "\nstarted_at: " + started_at.ToString() +
            "\nended_at: " + ended_at.ToString() +
            "\nevents: " + System.String.Join(", ", events.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
