//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class TaskMsg : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/Task";
        public override string RosMessageName => k_RosMessageName;

        //  One fulfilment task: move one item from its shelf slot to a drop-off pose.
        //  Poses are in the map frame (metres, radians).
        public const string CATEGORY_STANDARD = "Standard";
        public const string CATEGORY_HEAVY = "Heavy";
        public const string CATEGORY_FRAGILE = "Fragile";
        public int task_id;
        public int item_id;
        public string category;
        //  one of the CATEGORY_* constants
        public Geometry.Pose2DMsg shelf_pose;
        public Geometry.Pose2DMsg dropoff_pose;

        public TaskMsg()
        {
            this.task_id = 0;
            this.item_id = 0;
            this.category = "";
            this.shelf_pose = new Geometry.Pose2DMsg();
            this.dropoff_pose = new Geometry.Pose2DMsg();
        }

        public TaskMsg(int task_id, int item_id, string category, Geometry.Pose2DMsg shelf_pose, Geometry.Pose2DMsg dropoff_pose)
        {
            this.task_id = task_id;
            this.item_id = item_id;
            this.category = category;
            this.shelf_pose = shelf_pose;
            this.dropoff_pose = dropoff_pose;
        }

        public static TaskMsg Deserialize(MessageDeserializer deserializer) => new TaskMsg(deserializer);

        private TaskMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.item_id);
            deserializer.Read(out this.category);
            this.shelf_pose = Geometry.Pose2DMsg.Deserialize(deserializer);
            this.dropoff_pose = Geometry.Pose2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.Write(this.item_id);
            serializer.Write(this.category);
            serializer.Write(this.shelf_pose);
            serializer.Write(this.dropoff_pose);
        }

        public override string ToString()
        {
            return "TaskMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\nitem_id: " + item_id.ToString() +
            "\ncategory: " + category.ToString() +
            "\nshelf_pose: " + shelf_pose.ToString() +
            "\ndropoff_pose: " + dropoff_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
