//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class AttachItemRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/AttachItem";
        public override string RosMessageName => k_RosMessageName;

        //  /sim/attach_item - served by Unity (ItemCarrier).
        //  Re-parents the item GameObject onto the robot after the shelf dwell.
        public int item_id;

        public AttachItemRequest()
        {
            this.item_id = 0;
        }

        public AttachItemRequest(int item_id)
        {
            this.item_id = item_id;
        }

        public static AttachItemRequest Deserialize(MessageDeserializer deserializer) => new AttachItemRequest(deserializer);

        private AttachItemRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.item_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.item_id);
        }

        public override string ToString()
        {
            return "AttachItemRequest: " +
            "\nitem_id: " + item_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
