//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class AttachItemResponse : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/AttachItem";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        public string error;
        //  "" when ok

        public AttachItemResponse()
        {
            this.ok = false;
            this.error = "";
        }

        public AttachItemResponse(bool ok, string error)
        {
            this.ok = ok;
            this.error = error;
        }

        public static AttachItemResponse Deserialize(MessageDeserializer deserializer) => new AttachItemResponse(deserializer);

        private AttachItemResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "AttachItemResponse: " +
            "\nok: " + ok.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
