//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class FinishRunRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/FinishRun";
        public override string RosMessageName => k_RosMessageName;

        //  /metrics/finish_run - served by metrics_collector.
        //  Stops measuring and returns the complete summary.
        public string outcome;
        //  RunSummary.OUTCOME_*
        public string fail_reason;
        //  RunSummary.FAIL_*, "" on success

        public FinishRunRequest()
        {
            this.outcome = "";
            this.fail_reason = "";
        }

        public FinishRunRequest(string outcome, string fail_reason)
        {
            this.outcome = outcome;
            this.fail_reason = fail_reason;
        }

        public static FinishRunRequest Deserialize(MessageDeserializer deserializer) => new FinishRunRequest(deserializer);

        private FinishRunRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.outcome);
            deserializer.Read(out this.fail_reason);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.outcome);
            serializer.Write(this.fail_reason);
        }

        public override string ToString()
        {
            return "FinishRunRequest: " +
            "\noutcome: " + outcome.ToString() +
            "\nfail_reason: " + fail_reason.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
