//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class FinishRunResponse : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/FinishRun";
        public override string RosMessageName => k_RosMessageName;

        public RunSummaryMsg summary;

        public FinishRunResponse()
        {
            this.summary = new RunSummaryMsg();
        }

        public FinishRunResponse(RunSummaryMsg summary)
        {
            this.summary = summary;
        }

        public static FinishRunResponse Deserialize(MessageDeserializer deserializer) => new FinishRunResponse(deserializer);

        private FinishRunResponse(MessageDeserializer deserializer)
        {
            this.summary = RunSummaryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.summary);
        }

        public override string ToString()
        {
            return "FinishRunResponse: " +
            "\nsummary: " + summary.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
