//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class GetNextTaskResponse : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/GetNextTask";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        public TaskMsg task;
        public bool from_fallback;
        //  true = MySQL was down, bundled default task returned
        public string error;
        //  "" when ok

        public GetNextTaskResponse()
        {
            this.ok = false;
            this.task = new TaskMsg();
            this.from_fallback = false;
            this.error = "";
        }

        public GetNextTaskResponse(bool ok, TaskMsg task, bool from_fallback, string error)
        {
            this.ok = ok;
            this.task = task;
            this.from_fallback = from_fallback;
            this.error = error;
        }

        public static GetNextTaskResponse Deserialize(MessageDeserializer deserializer) => new GetNextTaskResponse(deserializer);

        private GetNextTaskResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            this.task = TaskMsg.Deserialize(deserializer);
            deserializer.Read(out this.from_fallback);
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.task);
            serializer.Write(this.from_fallback);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "GetNextTaskResponse: " +
            "\nok: " + ok.ToString() +
            "\ntask: " + task.ToString() +
            "\nfrom_fallback: " + from_fallback.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
