//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class GetNextTaskRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/GetNextTask";
        public override string RosMessageName => k_RosMessageName;

        //  /task_manager/get_next_task - served by task_manager (the only MySQL node).
        public string scenario_id;

        public GetNextTaskRequest()
        {
            this.scenario_id = "";
        }

        public GetNextTaskRequest(string scenario_id)
        {
            this.scenario_id = scenario_id;
        }

        public static GetNextTaskRequest Deserialize(MessageDeserializer deserializer) => new GetNextTaskRequest(deserializer);

        private GetNextTaskRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.scenario_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scenario_id);
        }

        public override string ToString()
        {
            return "GetNextTaskRequest: " +
            "\nscenario_id: " + scenario_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
