//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class MarkLegRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/MarkLeg";
        public override string RosMessageName => k_RosMessageName;

        //  /metrics/mark_leg - served by metrics_collector.
        //  Called when a leg starts, so replans are counted per leg and the
        //  drop-off mean speed only covers the drop-off leg.
        public const string LEG_SHELF = "shelf";
        public const string LEG_DROPOFF = "dropoff";
        public string leg;
        //  LEG_*

        public MarkLegRequest()
        {
            this.leg = "";
        }

        public MarkLegRequest(string leg)
        {
            this.leg = leg;
        }

        public static MarkLegRequest Deserialize(MessageDeserializer deserializer) => new MarkLegRequest(deserializer);

        private MarkLegRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.leg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.leg);
        }

        public override string ToString()
        {
            return "MarkLegRequest: " +
            "\nleg: " + leg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
