//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class MarkLegResponse : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/MarkLeg";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public MarkLegResponse()
        {
            this.ok = false;
        }

        public MarkLegResponse(bool ok)
        {
            this.ok = ok;
        }

        public static MarkLegResponse Deserialize(MessageDeserializer deserializer) => new MarkLegResponse(deserializer);

        private MarkLegResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "MarkLegResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
