//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class ReleaseItemRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/ReleaseItem";
        public override string RosMessageName => k_RosMessageName;

        //  /sim/release_item - served by Unity (ItemCarrier).
        //  Un-parents the item at the drop-off after the dwell.
        public int item_id;

        public ReleaseItemRequest()
        {
            this.item_id = 0;
        }

        public ReleaseItemRequest(int item_id)
        {
            this.item_id = item_id;
        }

        public static ReleaseItemRequest Deserialize(MessageDeserializer deserializer) => new ReleaseItemRequest(deserializer);

        private ReleaseItemRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.item_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.item_id);
        }

        public override string ToString()
        {
            return "ReleaseItemRequest: " +
            "\nitem_id: " + item_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
