//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class ReportRunResponse : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/ReportRun";
        public override string RosMessageName => k_RosMessageName;

        public bool stored;
        //  written to MySQL
        public bool buffered;
        //  saved to ~/.warehouse/pending/ instead
        public string error;
        //  "" when stored or buffered

        public ReportRunResponse()
        {
            this.stored = false;
            this.buffered = false;
            this.error = "";
        }

        public ReportRunResponse(bool stored, bool buffered, string error)
        {
            this.stored = stored;
            this.buffered = buffered;
            this.error = error;
        }

        public static ReportRunResponse Deserialize(MessageDeserializer deserializer) => new ReportRunResponse(deserializer);

        private ReportRunResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stored);
            deserializer.Read(out this.buffered);
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stored);
            serializer.Write(this.buffered);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "ReportRunResponse: " +
            "\nstored: " + stored.ToString() +
            "\nbuffered: " + buffered.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
