//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class ReportRunRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/ReportRun";
        public override string RosMessageName => k_RosMessageName;

        //  /task_manager/report_run - served by task_manager.
        //  Writes the run in one transaction, or buffers it to disk if MySQL is down.
        public RunSummaryMsg summary;

        public ReportRunRequest()
        {
            this.summary = new RunSummaryMsg();
        }

        public ReportRunRequest(RunSummaryMsg summary)
        {
            this.summary = summary;
        }

        public static ReportRunRequest Deserialize(MessageDeserializer deserializer) => new ReportRunRequest(deserializer);

        private ReportRunRequest(MessageDeserializer deserializer)
        {
            this.summary = RunSummaryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.summary);
        }

        public override string ToString()
        {
            return "ReportRunRequest: " +
            "\nsummary: " + summary.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
