//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class ResetScenarioRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/ResetScenario";
        public override string RosMessageName => k_RosMessageName;

        //  /sim/reset_scenario - served by Unity (ScenarioLoader).
        //  Loads the obstacle/NPC layout for a scenario and teleports the robot.
        public string scenario_id;
        //  S-00 .. S-05
        public Geometry.Pose2DMsg robot_start;
        //  map frame

        public ResetScenarioRequest()
        {
            this.scenario_id = "";
            this.robot_start = new Geometry.Pose2DMsg();
        }

        public ResetScenarioRequest(string scenario_id, Geometry.Pose2DMsg robot_start)
        {
            this.scenario_id = scenario_id;
            this.robot_start = robot_start;
        }

        public static ResetScenarioRequest Deserialize(MessageDeserializer deserializer) => new ResetScenarioRequest(deserializer);

        private ResetScenarioRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.scenario_id);
            this.robot_start = Geometry.Pose2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scenario_id);
            serializer.Write(this.robot_start);
        }

        public override string ToString()
        {
            return "ResetScenarioRequest: " +
            "\nscenario_id: " + scenario_id.ToString() +
            "\nrobot_start: " + robot_start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
