//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class SetCategoryRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/SetCategory";
        public override string RosMessageName => k_RosMessageName;

        //  /motion_profile/set_category - served by motion_profile_node.
        //  Applies the category's motion profile to move_base via dynamic_reconfigure.
        public string category;
        //  Task.CATEGORY_*

        public SetCategoryRequest()
        {
            this.category = "";
        }

        public SetCategoryRequest(string category)
        {
            this.category = category;
        }

        public static SetCategoryRequest Deserialize(MessageDeserializer deserializer) => new SetCategoryRequest(deserializer);

        private SetCategoryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.category);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.category);
        }

        public override string ToString()
        {
            return "SetCategoryRequest: " +
            "\ncategory: " + category.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
