//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class SetCategoryResponse : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/SetCategory";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        public string applied;
        //  category actually active (Fragile if applying failed)
        public string error;
        //  "" when ok

        public SetCategoryResponse()
        {
            this.ok = false;
            this.applied = "";
            this.error = "";
        }

        public SetCategoryResponse(bool ok, string applied, string error)
        {
            this.ok = ok;
            this.applied = applied;
            this.error = error;
        }

        public static SetCategoryResponse Deserialize(MessageDeserializer deserializer) => new SetCategoryResponse(deserializer);

        private SetCategoryResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            deserializer.Read(out this.applied);
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.applied);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "SetCategoryResponse: " +
            "\nok: " + ok.ToString() +
            "\napplied: " + applied.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
