//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Warehouse
{
    [Serializable]
    public class StartRunRequest : Message
    {
        public const string k_RosMessageName = "warehouse_msgs/StartRun";
        public override string RosMessageName => k_RosMessageName;

        //  /metrics/start_run - served by metrics_collector.
        //  Resets all counters and starts measuring a new episode.
        public string scenario_id;
        public string local_planner;
        //  dwa | teb
        public TaskMsg task;
        public Geometry.Pose2DMsg start_pose;
        //  robot start, map frame (for baseline_m)

        public StartRunRequest()
        {
            this.scenario_id = "";
            this.local_planner = "";
            this.task = new TaskMsg();
            this.start_pose = new Geometry.Pose2DMsg();
        }

        public StartRunRequest(string scenario_id, string local_planner, TaskMsg task, Geometry.Pose2DMsg start_pose)
        {
            this.scenario_id = scenario_id;
            this.local_planner = local_planner;
            this.task = task;
            this.start_pose = start_pose;
        }

        public static StartRunRequest Deserialize(MessageDeserializer deserializer) => new StartRunRequest(deserializer);

        private StartRunRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.scenario_id);
            deserializer.Read(out this.local_planner);
            this.task = TaskMsg.Deserialize(deserializer);
            this.start_pose = Geometry.Pose2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.scenario_id);
            serializer.Write(this.local_planner);
            serializer.Write(this.task);
            serializer.Write(this.start_pose);
        }

        public override string ToString()
        {
            return "StartRunRequest: " +
            "\nscenario_id: " + scenario_id.ToString() +
            "\nlocal_planner: " + local_planner.ToString() +
            "\ntask: " + task.ToString() +
            "\nstart_pose: " + start_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
